version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: diplom-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: med_schedule
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

